"use client";
import { useState, useEffect } from "react";
import LegalPage from "@/components/LegalPage";

type Lang = "en" | "pl";

function TermsEN() {
  return <>
    <p style={{ fontSize: 13, color: "#A09890", marginBottom: 32 }}>Last updated: March 2025</p>

    <h2>1. General</h2>
    <p>
      MikePrompt (&quot;Service&quot;) is operated by an individual based in Warsaw, Poland.
      By using this Service you agree to these terms.<br /><br />
      Contact: <a href="mailto:hello@mikeprompt.com">hello@mikeprompt.com</a>
    </p>

    <h2>2. Service Description</h2>
    <p>
      MikePrompt is a prompt optimization tool that improves text instructions for AI systems
      (ChatGPT, Claude, Gemini, etc.). We do not provide AI-generated content directly.
    </p>

    <h2>3. Acceptable Use</h2>
    <p>You agree not to:</p>
    <ul>
      <li>Use the Service for illegal purposes</li>
      <li>Process third-party personal data without consent</li>
      <li>Automate requests to bypass usage limits</li>
      <li>Resell or redistribute access to the Service</li>
    </ul>

    <h2>4. Disclaimer</h2>
    <p>
      THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND.
      We are not responsible for results generated by third-party AI systems.
      We do not guarantee 100% uptime.
    </p>

    <h2>5. Liability Limitation</h2>
    <p>
      To the maximum extent permitted by law, MikePrompt&apos;s liability is limited to
      the amount you paid for the Service in the last 3 months.
      For free users, liability is limited to €10.
    </p>

    <h2>6. Governing Law</h2>
    <p>
      These terms are governed by Irish law.
      EU users retain all consumer rights under their local law.
      Disputes shall be resolved in Dublin, Ireland.
    </p>

    <h2>7. Changes</h2>
    <p>
      We may update these terms with 14 days notice via email or site notice.
    </p>

    <p style={{ marginTop: 32, fontSize: 13, color: "#A09890" }}>
      Contact: <a href="mailto:hello@mikeprompt.com">hello@mikeprompt.com</a>
    </p>
  </>;
}

function TermsPL() {
  return <>
    <p style={{ fontSize: 13, color: "#A09890", marginBottom: 32 }}>Ostatnia aktualizacja: marzec 2025</p>

    <h2>1. Postanowienia ogólne</h2>
    <p>
      Serwis MikePrompt prowadzony jest przez osobę fizyczną z siedzibą w Warszawie, Polska.
      Korzystając z Serwisu akceptujesz niniejszy Regulamin.<br /><br />
      Kontakt: <a href="mailto:hello@mikeprompt.com">hello@mikeprompt.com</a>
    </p>

    <h2>2. Opis usługi</h2>
    <p>
      MikePrompt to narzędzie do optymalizacji promptów — poprawia instrukcje tekstowe
      kierowane do systemów AI (ChatGPT, Claude, Gemini i innych).
      Serwis nie generuje treści AI bezpośrednio.
    </p>

    <h2>3. Zasady korzystania</h2>
    <p>Użytkownik zobowiązuje się nie:</p>
    <ul>
      <li>Korzystać z Serwisu w celach niezgodnych z prawem</li>
      <li>Przetwarzać danych osobowych osób trzecich bez ich zgody</li>
      <li>Automatyzować zapytań w celu obejścia limitów</li>
      <li>Odsprzedawać ani redystrybuować dostępu do Serwisu</li>
    </ul>

    <h2>4. Wyłączenie gwarancji</h2>
    <p>
      SERWIS UDOSTĘPNIANY JEST &quot;TAK JAK JEST&quot; BEZ JAKICHKOLWIEK GWARANCJI.
      Nie ponosimy odpowiedzialności za wyniki generowane przez zewnętrzne systemy AI.
      Nie gwarantujemy 100% dostępności.
    </p>

    <h2>5. Ograniczenie odpowiedzialności</h2>
    <p>
      W maksymalnym zakresie dopuszczalnym przez prawo, odpowiedzialność MikePrompt
      ograniczona jest do kwoty zapłaconej za Serwis w ciągu ostatnich 3 miesięcy.
      Dla użytkowników bezpłatnych limit wynosi 10 €.
    </p>

    <h2>6. Prawo właściwe</h2>
    <p>
      Regulamin podlega prawu irlandzkiemu.
      Użytkownicy z UE zachowują wszystkie prawa konsumenckie wynikające z lokalnych przepisów.
      Spory rozstrzygane będą w Dublinie, Irlandia.
    </p>

    <h2>7. Zmiany Regulaminu</h2>
    <p>
      Regulamin może być aktualizowany z 14-dniowym wyprzedzeniem przekazywanym
      przez email lub komunikat na stronie.
    </p>

    <p style={{ marginTop: 32, fontSize: 13, color: "#A09890" }}>
      Kontakt: <a href="mailto:hello@mikeprompt.com">hello@mikeprompt.com</a>
    </p>
  </>;
}

export default function TermsPage() {
  const [lang, setLang] = useState<Lang>("en");

  useEffect(() => {
    const stored = localStorage.getItem("mikeprompt_lang");
    if (stored === "pl" || stored === "en") setLang(stored);
  }, []);

  const toggle = () => setLang(l => l === "pl" ? "en" : "pl");

  const title = lang === "pl" ? "Regulamin usługi" : "Terms of Service";

  return (
    <LegalPage title={title} lang={lang} onToggleLang={toggle}>
      {lang === "pl" ? <TermsPL /> : <TermsEN />}
    </LegalPage>
  );
}
